channels:
  - openbabel
  - rdkit
  - anaconda
  - conda-forge
  #- conda-forge/label/old_feature_broken  # this is needed for openmpi 3.0.0. TODO: check if this version is fine
  - e3sm
  - eumetsat
  - omnia
  - schrodinger
  - pytorch
  - ambermd
dependencies:
  - python==3.7.*
  - click
  - numpy==1.15.*
  - openbabel==2.4.*
  - rdkit==2019.09.*
  - pandas==0.24.*
  - scipy==1.4.*
  - path.py==11.5.*
  - treelib==1.5.*
  - Cython==0.29.*
  - networkx==2.4.*
  - tqdm
  - biopython
  - pymol==2.3.*
  - cmake==3.12.*
  - pytest
  - xmltodict
  - psutil
